# **The numpy pachage**

## **Introduction**

In [1]:
import numpy as np

In [2]:
list42 = list(range(1, 11))

In [3]:
list42

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np_list42 = np.array(list42)

In [5]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(np_list42)

numpy.ndarray

In [7]:
np_list42 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])