# **The numpy pachage**

## **Introduction**

In [1]:
import numpy as np

In [2]:
list42 = list(range(1, 11))

In [3]:
list42

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np_list42 = np.array(list42)

In [5]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(np_list42)

numpy.ndarray

In [7]:
np_list42 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arrays: Element-wise operations**

In [9]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [11]:
list43 = [1, 2, 3, 4]

In [12]:
list43

[1, 2, 3, 4]

In [13]:
list43 * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
list44 = []

In [15]:
for el in list43:
    list44.append(el * 2)

In [16]:
list44

[2, 4, 6, 8]

In [17]:
# can only concatenate list (not "int") to list
# list43 + 2

In [18]:
list45 = np.arange(1, 5)

In [19]:
list45

array([1, 2, 3, 4])

In [20]:
list45 * 2

array([2, 4, 6, 8])

In [21]:
list45 + 2

array([3, 4, 5, 6])

In [22]:
list45 ** 2

array([ 1,  4,  9, 16])

In [23]:
2 ** list45

array([ 2,  4,  8, 16], dtype=int32)

In [24]:
np.sqrt(list45)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [25]:
np.exp(list45)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [26]:
np.exp(1)

2.718281828459045

In [27]:
np.log(list45)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
list45.sum()

10

In [29]:
list45.mean()

2.5

## **Arrays: Indexing and slicing**

In [30]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np_list42[0]

1

In [32]:
np_list42[-1]

10

In [33]:
np_list42[-5]

6

In [34]:
np_list42[0:5]

array([1, 2, 3, 4, 5])

In [35]:
np_list42[5:]

array([ 6,  7,  8,  9, 10])

In [36]:
np_list42[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [37]:
np_list42[::2]

array([1, 3, 5, 7, 9])

In [38]:
np_list42[2::2]

array([3, 5, 7, 9])

In [39]:
list(enumerate(np_list42))

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [40]:
np_list42[0] = 42

In [41]:
np_list42

array([42,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# can only assign an iterable
# list42[1:4] = 43

In [43]:
np_list42[1:4] = 43

In [44]:
np_list42

array([42, 43, 43, 43,  5,  6,  7,  8,  9, 10])

In [45]:
np_list42[4:7] = [44, 45, 46]

In [46]:
np_list42

array([42, 43, 43, 43, 44, 45, 46,  8,  9, 10])

In [47]:
np_list43 = np_list42[2:8]

In [48]:
np_list43

array([43, 43, 44, 45, 46,  8])

In [49]:
np_list43[0] = 101

In [50]:
np_list43

array([101,  43,  44,  45,  46,   8])

In [51]:
np_list42

array([ 42,  43, 101,  43,  44,  45,  46,   8,   9,  10])

In [52]:
list46 = list(range(1, 11))

In [53]:
list46

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
list46_1 = list46[2:8]

In [55]:
list46_1

[3, 4, 5, 6, 7, 8]

In [56]:
list46_1[0] = 42

In [57]:
list46_1

[42, 4, 5, 6, 7, 8]

In [58]:
list46

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [59]:
np_list46 = np.arange(1,11)

In [60]:
np_list46

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np_list46_1 = np_list46[2:8].copy()

In [62]:
np_list46_1[0] = 42

In [63]:
np_list46_1

array([42,  4,  5,  6,  7,  8])

In [64]:
np_list46

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arrays: Shape and dimensions**

In [65]:
np_list47 = np.arange(1, 13)

In [66]:
np_list47

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np_list47.shape

(12,)

In [68]:
np_list47.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
np_list47

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
np_list47.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
np.reshape(np_list47, (3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
np_list47.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
np_list47.reshape(6, 2)[0:2, :]

array([[1, 2],
       [3, 4]])

In [74]:
# ValueError: cannot reshape array of size 12 into shape (3,5)
# np_list47.reshape(3,5)

In [75]:
np_list47.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## **Arrays: Indexing and slicing**

In [76]:
np_list48 = np.arange(1, 13)

In [77]:
np_list48.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
np_list48.reshape(3, 4, order = 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [79]:
np_list48 = np_list48.reshape(3, 4)

In [80]:
np_list48

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np_list48[0]

array([1, 2, 3, 4])

In [82]:
np_list48[1]

array([5, 6, 7, 8])

In [83]:
np_list48[0][0]

1

In [84]:
np_list48[1][1]

6

In [85]:
np_list48[1, 1]

6

In [86]:
np_list48[-1, -1]

12

In [87]:
np_list48[:, -1]

array([ 4,  8, 12])

In [88]:
type(np_list48[:, -1])

numpy.ndarray

In [89]:
np_list48[:, -1].shape

(3,)

In [90]:
np_list48.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [91]:
np_list48.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [92]:
np_list48[:, -1] / 4

array([1., 2., 3.])

In [93]:
np_list48[:, -1]  = np_list48[:, -1] / 4

In [94]:
np_list48

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  2],
       [ 9, 10, 11,  3]])

In [95]:
np_list48.sum()

60

In [96]:
np_list48.sum(axis = 0)

array([15, 18, 21,  6])

In [97]:
np_list48.sum(axis = 1)

array([ 7, 20, 33])

In [98]:
np_list48.cumsum()

array([ 1,  3,  6,  7, 12, 18, 25, 27, 36, 46, 57, 60])

In [99]:
np_list48.cumsum(axis = 0)

array([[ 1,  2,  3,  1],
       [ 6,  8, 10,  3],
       [15, 18, 21,  6]])

In [100]:
np_list48.cumsum(axis = 1)

array([[ 1,  3,  6,  7],
       [ 5, 11, 18, 20],
       [ 9, 19, 30, 33]])

In [101]:
np_list48.prod()

7484400

In [102]:
np_list48.prod(axis = 0)

array([ 45, 120, 231,   6])

In [103]:
np_list48.prod(axis = 1)

array([   6,  420, 2970])

In [104]:
np_list48.diagonal()

array([ 1,  6, 11])

In [105]:
np_list48.diagonal(offset = 1, axis1 = 1, axis2 = 0)

array([ 5, 10])

In [106]:
np_list48.diagonal(offset = -1)

array([ 5, 10])

In [107]:
np_list48.diagonal(offset = -1)

array([ 5, 10])

## **Arrays: Boolean indexing**

In [108]:
np_list49 = np.arange(1, 11)

In [109]:
mask1 = np_list49 > 5

In [110]:
mask1

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [111]:
np_list49[mask1]

array([ 6,  7,  8,  9, 10])

In [112]:
mask2 = (np_list49 > 5) & (np_list49 < 8)

In [113]:
np_list49[mask2]

array([6, 7])

In [114]:
mask3 = (np_list49 > 5) | (np_list49 < 8)

In [115]:
np_list49[mask3]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Random numbers**

In [116]:
a = np.random.randint(1, 101, 10)
a

array([44, 36, 98, 71, 56, 41, 77, 81, 80, 94])

In [117]:
np.random.seed(123)
b = np.random.randint(1, 101, 10)
b

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48])

In [118]:
c = np.random.normal(loc = 5, scale = 2, size = 10)
c

array([1.76139987, 2.77207117, 4.10511856, 8.33680322, 4.71325505,
       3.7616182 , 3.46113306, 6.15349204, 5.25305184, 2.39702205])

In [119]:
d = np.arange(1, 101)
d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [120]:
np.random.shuffle(d)

In [121]:
d

array([  5,   3,  96,  64,  73,  34,  37,  25,  67,  89,  17,  39,  30,
         9,   6,   1,  14,  80,  98,  87,  63,  38,  82,  33,  58,  29,
        66,  60,  32,  68,  20,  36,  74,  24,  10,  72, 100,  43,  46,
        47,  84,  75,  40,  95,  22,  12,  99,  88,  81,  61,  90,  97,
        42,  54,  45,  52,  69,  18,  79,  13,  50,  57,  21,  51,  26,
        56,  83,  44,   2,  55,  15,   7,  27,  71,  94,  31,  92,  16,
        19,  78,  23,  11,  59,  91,  76,  65,  70,   4,  41,  77,  35,
        28,  86,  53,  93,   8,  49,  62,  48,  85])

In [122]:
d.sort()
d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [123]:
d[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [124]:
d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [125]:
np.random.seed(123)
d1 = np.random.choice(d, size = 100, replace = True)
d1

array([ 67,  93,  99,  18,  84,  58,  87,  98,  97,  48,  74,  33,  47,
        97,  26,  84,  79,  37,  97,  81,  69,  50,  56,  68,   3,  85,
        40,  67,  85,  48,  62,  49,   8, 100,  93,  53,  98,  86,  95,
        28,  35,  98,  77,  41,   4,  70,  65,  76,  35,  59,  11,  23,
        78,  19,  16,  28,  31,  53,  71,  27,  81,   7,  15,  76,  55,
        72,   2,  44,  59,  56,  26,  51,  85,  57,  50,  13,  19,  82,
         2,  52,  45,  49,  57,  92,  50,  87,   4,  68,  12,  22,  90,
        99,   4,  12,   4,  95,   7,  10,  88,  15])

In [126]:
d1.sort()
d1

array([  2,   2,   3,   4,   4,   4,   4,   7,   7,   8,  10,  11,  12,
        12,  13,  15,  15,  16,  18,  19,  19,  22,  23,  26,  26,  27,
        28,  28,  31,  33,  35,  35,  37,  40,  41,  44,  45,  47,  48,
        48,  49,  49,  50,  50,  50,  51,  52,  53,  53,  55,  56,  56,
        57,  57,  58,  59,  59,  62,  65,  67,  67,  68,  68,  69,  70,
        71,  72,  74,  76,  76,  77,  78,  79,  81,  81,  82,  84,  84,
        85,  85,  85,  86,  87,  87,  88,  90,  92,  93,  93,  95,  95,
        97,  97,  97,  98,  98,  98,  99,  99, 100])

In [127]:
np.unique(d1)

array([  2,   3,   4,   7,   8,  10,  11,  12,  13,  15,  16,  18,  19,
        22,  23,  26,  27,  28,  31,  33,  35,  37,  40,  41,  44,  45,
        47,  48,  49,  50,  51,  52,  53,  55,  56,  57,  58,  59,  62,
        65,  67,  68,  69,  70,  71,  72,  74,  76,  77,  78,  79,  81,
        82,  84,  85,  86,  87,  88,  90,  92,  93,  95,  97,  98,  99,
       100])

## **Performance issues**

In [137]:
size = 1000000

In [138]:
x = list(range(size))
len(x)

1000000

In [139]:
z = np.arange(size)
len(z)

1000000

In [140]:
%timeit [i + 2 for i in x]

34 ms ± 225 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [141]:
%timeit z + 2

610 µs ± 2.39 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [142]:
%timeit [i ** 2 for i in x]

42 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [143]:
%timeit z ** 2

613 µs ± 5.93 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## **Case study**