# **The numpy pachage**

## **Introduction**

In [1]:
import numpy as np

In [2]:
list42 = list(range(1, 11))

In [3]:
list42

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np_list42 = np.array(list42)

In [5]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(np_list42)

numpy.ndarray

In [7]:
np_list42 * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arrays: Element-wise operations**

In [9]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [11]:
list43 = [1, 2, 3, 4]

In [12]:
list43

[1, 2, 3, 4]

In [13]:
list43 * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
list44 = []

In [15]:
for el in list43:
    list44.append(el * 2)

In [16]:
list44

[2, 4, 6, 8]

In [17]:
# can only concatenate list (not "int") to list
# list43 + 2

In [18]:
list45 = np.arange(1, 5)

In [19]:
list45

array([1, 2, 3, 4])

In [20]:
list45 * 2

array([2, 4, 6, 8])

In [21]:
list45 + 2

array([3, 4, 5, 6])

In [22]:
list45 ** 2

array([ 1,  4,  9, 16])

In [23]:
2 ** list45

array([ 2,  4,  8, 16], dtype=int32)

In [24]:
np.sqrt(list45)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [25]:
np.exp(list45)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [26]:
np.exp(1)

2.718281828459045

In [27]:
np.log(list45)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
list45.sum()

10

In [29]:
list45.mean()

2.5

## **Arrays: Indexing and slicing**

In [30]:
np_list42

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np_list42[0]

1

In [32]:
np_list42[-1]

10

In [33]:
np_list42[-5]

6

In [34]:
np_list42[0:5]

array([1, 2, 3, 4, 5])

In [35]:
np_list42[5:]

array([ 6,  7,  8,  9, 10])

In [36]:
np_list42[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [37]:
np_list42[::2]

array([1, 3, 5, 7, 9])

In [38]:
np_list42[2::2]

array([3, 5, 7, 9])

In [39]:
list(enumerate(np_list42))

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [40]:
np_list42[0] = 42

In [41]:
np_list42

array([42,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# can only assign an iterable
# list42[1:4] = 43

In [43]:
np_list42[1:4] = 43

In [44]:
np_list42

array([42, 43, 43, 43,  5,  6,  7,  8,  9, 10])

In [45]:
np_list42[4:7] = [44, 45, 46]

In [46]:
np_list42

array([42, 43, 43, 43, 44, 45, 46,  8,  9, 10])

In [47]:
np_list43 = np_list42[2:8]

In [48]:
np_list43

array([43, 43, 44, 45, 46,  8])

In [49]:
np_list43[0] = 101

In [50]:
np_list43

array([101,  43,  44,  45,  46,   8])

In [51]:
np_list42

array([ 42,  43, 101,  43,  44,  45,  46,   8,   9,  10])

In [52]:
list46 = list(range(1, 11))

In [53]:
list46

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [54]:
list46_1 = list46[2:8]

In [55]:
list46_1

[3, 4, 5, 6, 7, 8]

In [56]:
list46_1[0] = 42

In [57]:
list46_1

[42, 4, 5, 6, 7, 8]

In [58]:
list46

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [59]:
np_list46 = np.arange(1,11)

In [60]:
np_list46

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np_list46_1 = np_list46[2:8].copy()

In [62]:
np_list46_1[0] = 42

In [63]:
np_list46_1

array([42,  4,  5,  6,  7,  8])

In [64]:
np_list46

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arrays: Shape and dimensions**

In [65]:
np_list47 = np.arange(1, 13)

In [66]:
np_list47

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np_list47.shape

(12,)

In [68]:
np_list47.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
np_list47

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
np_list47.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
np.reshape(np_list47, (3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
np_list47.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
np_list47.reshape(6, 2)[0:2, :]

array([[1, 2],
       [3, 4]])

In [74]:
# ValueError: cannot reshape array of size 12 into shape (3,5)
# np_list47.reshape(3,5)

In [75]:
np_list47.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## **Arrays: Indexing and slicing**

In [76]:
np_list48 = np.arange(1, 13)

In [77]:
np_list48.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
np_list48.reshape(3, 4, order = 'F')

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [79]:
np_list48 = np_list48.reshape(3, 4)

In [80]:
np_list48

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np_list48[0]

array([1, 2, 3, 4])

In [82]:
np_list48[1]

array([5, 6, 7, 8])

In [83]:
np_list48[0][0]

1

In [84]:
np_list48[1][1]

6

In [85]:
np_list48[1, 1]

6

In [86]:
np_list48[-1, -1]

12

In [87]:
np_list48[:, -1]

array([ 4,  8, 12])

In [88]:
type(np_list48[:, -1])

numpy.ndarray

In [89]:
np_list48[:, -1].shape

(3,)

In [90]:
np_list48.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [91]:
np_list48.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [92]:
np_list48[:, -1] / 4

array([1., 2., 3.])

In [93]:
np_list48[:, -1]  = np_list48[:, -1] / 4

In [94]:
np_list48

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  2],
       [ 9, 10, 11,  3]])

In [95]:
np_list48.sum()

60

In [96]:
np_list48.sum(axis = 0)

array([15, 18, 21,  6])

In [97]:
np_list48.sum(axis = 1)

array([ 7, 20, 33])

In [98]:
np_list48.cumsum()

array([ 1,  3,  6,  7, 12, 18, 25, 27, 36, 46, 57, 60])

In [99]:
np_list48.cumsum(axis = 0)

array([[ 1,  2,  3,  1],
       [ 6,  8, 10,  3],
       [15, 18, 21,  6]])

In [100]:
np_list48.cumsum(axis = 1)

array([[ 1,  3,  6,  7],
       [ 5, 11, 18, 20],
       [ 9, 19, 30, 33]])

In [101]:
np_list48.prod()

7484400

In [107]:
np_list48.prod(axis = 0)

array([ 45, 120, 231,   6])

In [108]:
np_list48.prod(axis = 1)

array([   6,  420, 2970])

In [102]:
np_list48.diagonal()

array([ 1,  6, 11])

In [103]:
np_list48.diagonal(offset = 1, axis1 = 1, axis2 = 0)

array([ 5, 10])

In [104]:
np_list48.diagonal(offset = -1)

array([ 5, 10])

In [105]:
np_list48.diagonal(offset = -1)

array([ 5, 10])